### ISSUE TITLE
compiling issue

### ISSUE THREAD

**Issue by mastersani** [me-asri/rtptun#1]
Hello dear when we compile in centos 7 only getting error 
src/client.c: In function ‘rtptun_client_new’:
src/client.c:57:5: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
     ev_timer_init(&client->to_timer, timeout_cb, 0, RTPTUN_TIMEOUT);
packge allready installed

**Comment by me-asri** [comment]
Chances are this is due to CentOS 7 using an ancient version of GCC.
You could either use a newer version of GCC (I recommend using GCC 8.x at minimum).
Or you could simply remove the -Werror flag from CFLAGS_REL and ignore the resulting warnings:
`make CFLAGS_REL=-O3 -j$(nproc)`

**Comment by mastersani** [comment]
Thanks alot dude for quick response. If you don.t mind can you give me any skype id whatsup 

Sent from Yahoo Mail on Android 
 
  On Sat, Dec 24, 2022 at 8:43 AM, Mehrzad ***@***.***> wrote:   


Chances are this is due to CentOS 7 using an ancient version of GCC.
You could either use a newer version of GCC (I recommend using GCC 8.x at minimum).
Or you could simply remove the -Werror flag from CFLAGS_REL and ignore the resulting warnings:
make CFLAGS_REL=-O3 -j$(nproc)

**Comment by me-asri** [comment]
> If you don.t mind can you give me any skype id whatsup

That I can't do, but I'd gladly help with any issues regarding rtptun here.
